version: '3.7'

services:
  server:
    image: server:local
    container_name: server
    ports:
      - 8000:8000
    restart: unless-stopped

  ui:
    image: ui:local
    container_name: ui
    ports:
      - 8080:80
